stages:
  - build
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

build-and-push:
  stage: build
  image: docker:27
  tags:
    - pipeline
  services:
    - name: docker:27-dind
      command: ["--insecure-registry=10.1.0.11:5050", "--tls=false"]
  before_script:
    - until docker info > /dev/null 2>&1; do echo "Waiting for Docker daemon..."; sleep 2; done
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - main

deploy:
  stage: deploy
  image: alpine/git:latest
  tags:
    - pipeline
  script:
    - git clone http://oauth2:$GITOPS_TOKEN@10.1.0.11/devops/cluster-charts.git
    - cd cluster-charts
    - 'sed -i "s/  tag:.*/  tag: $IMAGE_TAG/" gallery-backend/values.yaml'
    - git config user.email "ci@boukingolts.art"
    - git config user.name "GitLab CI"
    - git add gallery-backend/values.yaml
    - 'git commit -m "ci: update gallery-backend image to $IMAGE_TAG"'
    - git push
  only:
    - main
